export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';

export const FETCH_BLOGS = 'FETCH_BLOGS';
export const FETCH_BLOGS_FAILED = 'FETCH_BLOGS_FAILED';
export const FETCH_SELECTED_BLOG = 'FETCH_SELECTED_BLOG';
export const FETCH_SELECTED_BLOG_FAILED = 'FETCH_SELECTED_BLOG_FAILED';
